### ISSUE TITLE
Model registry: A proposal

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#618]
We have previously suggested registering models to allow for reproducibility. We also include a lot of metadata on the benchmark leaderboard, which would be nice to register along with the model. My suggestion is as follows:

Implement a model class as follows:
```
ModelMeta:
   loader = Callable[..., Encoder] | None # if None it will just default to loading the sentence trf. model 
   name: str # ideally name on hugginface
   n_parameters: int
   memory_usage: float
   max_tokens: int
   embedding_dimension: int
   revision: int
   release_date: datetime  # useful for tracking improvement over time on given task
   license: str | None  # required if open source 
   open_source: bool # "Poprietary" / "Open" # we could remove this in favor of license
   framework: list[literal["Sentence Transformers", "PyTorch", ...]]
  languages: list[Language] # language the model is intended for   
```

I would expect the user interface to be something like so:
```
model_with_meta = mteb.get_model("intfloat/multilingual-e5-large")
tasks = mteb.get_tasks("eng")

benchmark = MTEB(tasks = tasks)
benchmark.run(model_with_meta)
# or
encoder = model_with_meta.load_encoder()
benchmark.run(encoder) # this is the current interface
```

What I am looking for is:
- do you agree with this approach (a thumbs up will do)
- Any metadata which we should add or remove
- Any changes to the user interface

> Related to #314 and also implemented in the [Scandinavian embedding benchmark](https://github.com/KennethEnevoldsen/scandinavian-embedding-benchmark/). Also previously discussed in #475.

Tagging relevant contributors:
- @tomaarsen, this likely affects the leaderboard
- @Muennighoff, @imenelydiaker, @x-tabdeveloping, @orionw @isaac-chung, as we discussed during the meeting.
